### ISSUE TITLE
correct package installation

### ISSUE THREAD

**Issue by dimalvovs** [aschein/prgpmf#1]
Hey, thank you for sharing this with the world! 

I was trying to install the package, and after tweaking my system as well as the setup.py to make sure all paths are found correctly, stumbled upon something that I cannot easily adress:

```
base/allocate.pyx:35:8: undeclared name not builtin: gsl_rng_set

Error compiling Cython file:
------------------------------------------------------------
...
    def __dealloc__(self):
        """
        Free GSL random number generator.
        """

        gsl_rng_free(self.rng)
        ^
------------------------------------------------------------

base/allocate.pyx:42:8: undeclared name not builtin: gsl_rng_free
Traceback (most recent call last):
  File "/Users/me/Documents/jhu/prgpmf/src/apf/setup.py", line 57, in <module>
    ext_modules=cythonize(exts),
  File "/Users/me/envs/prgmf@10/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/Users/me/envs/prgmf@10/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: base/allocate.pyx
```

Is this something seen before, and if yes, how could I address it? More general, should I be able to install on a Mac?

Mac M2 15.0.1 (24A348)

**Comment by dimalvovs** [comment]
note - all the other `.pyx` files build fine
